# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:12
from __future__ import unicode_literals

import django.db.models.deletion

from django.db import migrations, models
from django.conf import settings
from django.utils.translation import gettext as _

from invoice import app_settings
from invoice import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(app_settings.ADDRESS_MODEL),
        migrations.swappable_dependency(app_settings.BANK_ACCOUNT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('name', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('business_id', models.CharField(blank=True, max_length=12, null=True, verbose_name=_('Business ID'))),
                ('tax_id', models.CharField(blank=True, max_length=15, null=True, verbose_name=_('Tax ID'))),
                ('extra', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': _('Address'),
                'verbose_name_plural': _('Addresses'),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('prefix', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name=_('Prefix'))),
                ('number', models.DecimalField(decimal_places=0, max_digits=16, verbose_name=_('Account number'))),
                ('bank', models.DecimalField(decimal_places=0, max_digits=4, verbose_name=_('Bank code'))),
            ],
            options={
                'verbose_name': _('Bank account'),
                'verbose_name_plural': _('Bank accounts'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('uid', models.CharField(blank=True, max_length=10, unique=True)),
                ('logo', models.FilePathField(blank=True, match='.*(png|jpg|jpeg|svg)', null=True)),
                ('state', models.CharField(choices=[('proforma', _('Proforma')), ('invoice', _('Invoice'))], default='proforma', max_length=15)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('date_due', models.DateField(default=utils.in_14_days)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=_('Date added'))),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=_('Last modified'))),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=app_settings.ADDRESS_MODEL)),
                ('contractor_bank', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=app_settings.BANK_ACCOUNT_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=app_settings.ADDRESS_MODEL)),
                ('subscriber_shipping', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=app_settings.ADDRESS_MODEL)),
            ],
            options={
                'verbose_name': _('Invoice'),
                'verbose_name_plural': _('Invoices'),
                'ordering': ('-date_issued', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('description', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=4)),
                ('tax', models.DecimalField(decimal_places=0, max_digits=3)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.Invoice')),
            ],
            options={
                'verbose_name': _('Invoice item'),
                'verbose_name_plural': _('Invoice items'),
                'ordering': ['unit_price'],
            },
        ),
    ]
